### PR TITLE
Try to deal with #46

### PR DESCRIPTION
**Pull request by back2dos**

### CODE REVIEW

**Comment by back2dos** [comment]
Seems to work fine as indicated by the tests. I'm slightly hesitant to add more implicit casts at this point, but this one seems specific enough.

Also, using GADTs is always fun until it isn't. In this case, postfix `switch` autocompletion fails:

GADT-vs-IDE

Anyway, if people could confirm that this doesn't blow up everything else for them, I guess we can merge it.

**Comment by kevinresol** [comment]
The diff looks good in my codebase :+1:

**Comment by back2dos** [comment]
Well, seems to work fine for me, so let's do this.

**Comment by nadako** [comment]
Wow this is neat :) I'm also surprised that Haxe handles this pattern matching properly figuring out that there can be no `Failed` case.

**Pull request merged**
