### PR TITLE
Expose the max iteration number

### PR DESCRIPTION
**Pull request by kevinresol**

### CODE REVIEW

**Comment by back2dos** [comment]
Fine by me. That said, `Measurement` based observables have relatively poor performance characteristics, so you may want to avoid them ;)

**Comment by kevinresol** [comment]
I dunno what is Measurement based observable tbh. But I am having issue with a observable that has a very deep and broad dependency in coconut.data

**Comment by kevinresol** [comment]
My code is something like this:

```haxe
@:observable var list:List<...>;
@:computed var count:Int = list.count(v -> v.observableBool);
```

the list is of size ~100 and each of the `observableBool` depends on another 2-3 observables.
and I got the error from AutoObservable (the error message is: no result after N attempts) rather than `SimpleObservable`

**Comment by back2dos** [comment]
Hmm. That's odd.

Basically, when recomputing, the logic goes something like this:

```haxe
while (!valid) {
  valid = true;
  computation();
}
```

So *if* the computation invalidates the result, it is rerun. Ideally, computations have no side effects, and therefore do not invalidate anything. Sometimes, it's more practical to do that, but if it happens >100 in a single observable, something is weird, either in tink_state or in your code ^^

**Comment by kevinresol** [comment]
Is there a way to know what is being invalidated and causes the rerun? I don't think I have code that invalidate stuff during computation...

**Comment by back2dos** [comment]
Well, it's still a little crude, but you can compile with `-D tink_state.debug`, then subclass `tink.state.debug.Logger` to override [`triggered`](https://github.com/haxetink/tink_state/blob/3ec6edcadfbd9d6dc6b86af857ac2ab24dcc29ea/src/tink/state/debug/Logger.hx#L10) and then add that logger.

**Pull request merged**
