### PR TITLE
Add Progress

### PR DESCRIPTION
**Pull request by kevinresol**
This is a type that represents a progress (0% - 100%) and the finished result

```haxe
var trigger = Progress.trigger(); // maybe needs a better function name
var progress = state.asProgress();

// observes the ProgressValue, auto-dissolves once a result is resolved
progress.bind(v -> trace(v));  // e.g. Pair(0.5, Some(1.0))

// gives the result as Future<T>
progress.result(); 

// added .next() to make it behaves like a Future/Promise
progress.next(result -> result.length); 

// set the current progress and total value
trigger.progress(0.5, Some(1.0)); 

// complete with a value
trigger.finish('Done'); 
```

perhaps we can use this as the return value of `tink.http.Client.request`

### CODE REVIEW

**Comment by kevinresol** [comment]
I wonder if the max value should be configurable. So it could be used to represent the "actual progress" (instead of the percentage progress currently) like bytesLoaded.

e.g. for response that has content-length, we could set max = that length. for those doesn't, we could set max = POSITIVE_INFINITY

something like this:

```haxe
var progress:Progress<Chunk> = response.all();
progress.max; // = content-length
progress.value; // = bytesloaded
progress.progress(loaded -> trace(loaded / progress.max));
```

**Comment by back2dos** [comment]
Looks good to me. I have two comments:

- While I can see how this is useful, I'm not 100% sure this lib is the best place for it. Then again I have no counter proposal, so feel free to merge, if you can't think of a better place either ;)
- Not sure if the `< 1` restriction is a good choice. I've often seen progress indicators that hang at 100% for a moment, because the actual completion requires a second step or the progress metric is simply a rough estimation. If we skip the update, then information (inaccurate as it may be) gets dropped.

**Comment by back2dos** [comment]
As for the other question: I think relative progress is usually easier to deal with. When you use this to display a progress indicator, you'd transform absolute progress to relative one. That said,  having a `totalBytes` (defaulting to `-1` perhaps? or perhaps make it an `Option<Int>`?) that carries around this information for those who care is probably useful.

**Comment by kevinresol** [comment]
You can't set progress to 1 manually, because it is [implied from the finished value](https://github.com/haxetink/tink_state/pull/14/files#diff-2e7eacc80339272a8197f726a1f58ca8R42).

Okay let me put a `total:Option<Int>` there then.

**Comment by back2dos** [comment]
I understand that having a result implies 100% progress, but the converse is not true: you can very well measure 100% progress without having a result yet, if either the measurement is a relatively crude estimate or does not include a second post-processing step (e.g. in the good old days a `flash.display.Loader` would hit the 100% bytes loaded, but would actually be done after the SWF was parsed and initialized). Perhaps I'm splitting hair though ^^

**Comment by kevinresol** [comment]
Turns out I put the total value into the progress update call. Because I have even encountered some progress bar that would have both the current and total value increasing over time. Also, we can't know the total value (if it is a constant) in advance if we want to flatten `Future<Progress>`.

(Example in OP updated)

**Comment by kevinresol** [comment]
Function-wise I think this fits in tink_core, but I don't think we want it to have dependencies?

**Comment by back2dos** [comment]
Uh, sorry. Yeah, here's fine :)

**Pull request merged**
